services:
  app:
    image: rokaia011/liliarukayiangelica-app
    depends_on:
      - database
    networks:
      - project-network

  database:
    image: rokaia011/liliarukayiangelica-postgres
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - project-network

volumes:
  db_data:

networks:
  project-network:

