version: "3.8"

services:
  database:
    image: rokaia011/liliarukayiangelica-postgres
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: projectpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - project-network
  app:
    image: rokaia011/liliarukayiangelica-app
    depends_on:
      - database
    networks:
      - project-network
volumes:
  db_data:

networks:
  project-network:
